Resolves the "error C2445: result type of conditional expression is ambiguous: types 'const char [..]' and 'G4Sting' can be converted to multiple common types" by adding explicit construction of G4String from the string literal.